[package]
name = "rust-github-action-test-b76u22ivt4z3"
version = "9999999999999999999.9999999999999999999.8999999999999999999"
edition = "2021"
description = "A simple Rust project to test GitHub Actions!"
readme = "README.md"
repository = "https://github.com/Nakanishi123/rust-github-action-test-b76u22ivt4z3"
license = "AGPL-3.0-only"

[dependencies]
